name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
jobs:
  deploy:
    name: CD
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: rollout restart -n premid deployment/website-${{ steps.extract_branch.outputs.branch }}
