name: DePloY
on:
  push:
    branches: master
    paths:
      - "public/**/*"
      - "src/**/*"
      - "package.json"
      - "**.js"
      - "yarn.lock"
      - "**/*.yml"
jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/PreMiD/Website/Master
            git reset --hard
            git pull
            yarn
            yarn build
            cp -r dist/* /var/www/html/premidBeta
